[package]
name = "rust_broadcast_server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
tokio = { version = "1.38", features = ["full"] }

[[bin]]
name = "server"
path = "src/server.rs"